[package]
name = "clock-proxy"
version = "0.1.0"
edition = "2021"

[lib]
name = "clock_pb"
path = "lib/clock_pb.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"

[dependencies]
# The current 0.2 release has a broken `serde` build.
hass-rs = { git = "https://github.com/danrusei/hass-rs", rev="a51d02c3202568076b6bc093466ad0277a812946", default-features = false, features = ["tokio-runtime"] }
tokio = { version = "1", features = ["full"] }
lazy_static = "1.4.0"
tonic = "0.9.2"
prost = "0.11"

[build-dependencies]
tonic-build = "0.9.2"
