[package]
name = "clock"
version = "0.1.0"
edition = "2021"

[lib]
name = "lib"
path = "lib/lib.rs"

[[bin]]
name = "display"
path = "src/display/main.rs"

[[bin]]
name = "exporter"
path = "src/exporter/main.rs"

[dependencies]
# The current 0.2 release has a broken `serde` build.
hass-rs = { git = "https://github.com/danrusei/hass-rs", rev="a51d02c3202568076b6bc093466ad0277a812946", default-features = false, features = ["tokio-runtime"] }
tokio = { version = "1", features = ["full"] }
tonic = "0.9.2"
prost = "0.11"
log = "0.4.19"
env_logger = "0.10.0"

[build-dependencies]
tonic-build = "0.9.2"
