services:
  display:
    container_name: display
    image: hnefatl/people-display
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/files/display_config
      - DISPLAY=:0
    volumes:
      - /files:/files
      - /tmp/:/tmp/

  # Run watchtower to autoupdate containers.
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP
      - WATCHTOWER_ROLLING_RESTART
      # 1hr, so that any rare patches I make take effect quickly
      - WATCHTOWER_POLL_INTERVAL=3600 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
