services:
  display:
    container_name: display
    image: hnefatl/people-display
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/files/display_config
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp
    volumes:
      - /files:/files
      - /tmp/:/tmp/

  # Run watchtower to autoupdate containers.
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP
      - WATCHTOWER_ROLLING_RESTART
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
