name: "Docker Image: Display"

on:
  push:
    tags:
      - 'display*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx to enable docker build cache
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Extract commit version
      id: metadata
      uses: docker/metadata-action@v4
      with:
        images: hnefatl/people-display

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        file: display.Dockerfile
        context: .
        push: true
        # Compile for raspberry pi.
        platforms: linux/arm64,linux/amd64
        tags: ${{ steps.metadata.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
