name: Build and publish Exporter

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Extract commit version
      id: metadata
      uses: docker/metadata-action@v4
      with:
        images: hnefatl/people-display

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        file: exporter.Dockerfile
        context: .
        push: true
        tags: ${{ steps.metadata.outputs.tags }}

